### ISSUE TITLE
aggregator error

### ISSUE THREAD

**Issue by cwulfman** [agile-humanities/ddhi-aggregator#1]
Bill Kennedy posted this report in Asana:

The ddhi aggregator throws the following error:

ddhi_aggregate -i /Users/bill/Sites/ddhi-repository-d8/data/staging/TEI_Encoding/transcripts -o /Users/bill/Sites/ddhi-repository-d8/data/aggregates
Traceback (most recent call last):
  File "/usr/local/bin/ddhi_aggregate", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.9/site-packages/ddhi_aggregator/aggregate.py", line 94, in run
    main(sys.argv[1:])
  File "/usr/local/lib/python3.9/site-packages/ddhi_aggregator/aggregate.py", line 87, in main
    aggregate_tei(args.source_dir, args.target_dir)
  File "/usr/local/lib/python3.9/site-packages/ddhi_aggregator/aggregate.py", line 28, in aggregate_tei
    aggregator.aggregate()
  File "/usr/local/lib/python3.9/site-packages/ddhi_aggregator/aggregators/aggregators.py", line 72, in aggregate
    self.include(interview)
  File "/usr/local/lib/python3.9/site-packages/ddhi_aggregator/aggregators/aggregators.py", line 109, in include
    [self.aggregate_date(Date(date)) for date in interview.dates()]

**Comment by cwulfman** [comment]
I updated the package to version 1.0.0 and uploaded to pypi; I then created a clean Ubuntu 20.04 vm and installed the package there, where it worked without this issue.
